kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpoppdrag
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /fpoppdrag/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fpoppdrag/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fpoppdrag/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: {{oracleconfigpath}}
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath: {{oraclesecretpath}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{serviceusersecretpath}}
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/{{environment}}
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
        - application: fp-frontend-azure
          cluster: dev-fss
  secureLogs:
    enabled: true
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
