kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpoppdrag
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image:  {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fpoppdrag/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fpoppdrag/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fpoppdrag/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  {{oraclesecretpath}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{serviceusersecretpath}}
  azure:
    application:
      enabled: true
  webproxy: true
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}

---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamforeldrepenger
  name: fpoppdrag-swagger
  namespace: teamforeldrepenger
spec:
  image: ghcr.io/navikt/swaggerapi/swagger-ui:latest
  port: 8080
  ingresses:
    - "https://fpoppdrag-q1.nais.preprod.local",
    - "https://app-q1.adeo.no/fpoppdrag",
    - "https://fpoppdrag.dev.intern.nav.no/"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  env:
    - name: SWAGGER_JSON
      value: ""
    - name: BASE_URL
      value: "/swagger"
    - name: URL
      value: "/fpoppdrag/internal/api/openapi.json"
#  accessPolicy:
#    inbound:
#      rules:
#        - application: fp-frontend
#        - application: fpsak-redis-exporter

