apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamforeldrepenger
  name: fpoppdrag-swagger
  namespace: teamforeldrepenger
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: ghcr.io/navikt/swaggerapi/swagger-ui:latest
  port: 8080
  ingresses:
    - "https://fpswagger.dev.intern.nav.no"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  env:
    - name: SWAGGER_JSON
      value: ""
    - name: BASE_URL
      value: "/swagger"
    - name: WITH_CREDENTIALS
      value: "true"
    - name: URLS
      value: "[{url: 'https://fpoppdrag.dev.intern.nav.no/fpoppdrag/api/openapi.yaml', name: 'fpoppdrag '},{url: 'https://fpformidling.dev.intern.nav.no/fpformidling/api/openapi.yaml', name: 'fpformidling'},{url: 'https://fptilbake.dev.intern.nav.no/fptilbake/api/openapi.yaml', name: 'fptilbake'}]"
#  accessPolicy:
#    inbound:
#      rules:
#        - application: fp-frontend
#        - application: fpsak-redis-exporter

