Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('FAGSYSTEM','GSak',null,null,'Fagsystemer','N','N','Fagsystemer','NAV Fagsystemer','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('MOTTAKER_TYPE','VL',null,null,'MottakerTyper','N','N','MottakerTyper','Mottaker typer i simulering','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('FAG_OMRAADE_KODE','VL',null,null,'FagOmraadeKoder','N','N','FagOmraadeKoder','Fag Omraader Koder i simulering','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('BETALING_TYPE','VL',null,null,'BetalingTyper','N','N','BetalingTyper','Betaling typer i simulering','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('POSTERING_TYPE','VL',null,null,'PosteringTyper','N','N','PosteringTyper','Postering typer i simulering','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('KLASSE_KODE','VL',null,null,'KlasseKoder','N','N','KlasseKoder','Klasse koder i simulering','N');