DROP TABLE OKO_ATTESTANT_180;
DROP TABLE OKO_GRAD_170;
DROP TABLE OKO_REFUSJONSINFO_156;
DROP TABLE OKO_OPPDRAG_LINJE_150;
DROP TABLE OKO_OPPDRAG_ENHET_120;
DROP TABLE OKO_OMPOSTERING_116;
DROP TABLE OKO_AVSTEMMING_115;
DROP TABLE OPPDRAG_KVITTERING;
DROP TABLE OKO_OPPDRAG_110;
DROP TABLE OPPDRAG_KONTROLL;
DROP TABLE TY_FERIEPENGER;
DROP TABLE TILKJENT_YTELSE_ANDEL;
DROP TABLE TILKJENT_YTELSE_PERIODE;
DROP TABLE TY_BEHANDLING_INFO;
DROP TABLE TILKJENT_YTELSE;

DROP SEQUENCE SEQ_OPPDRAG_KONTROLL;
DROP SEQUENCE SEQ_OKO_AVSTEMMING_115;
DROP SEQUENCE SEQ_OKO_OPPDRAG_110;
DROP SEQUENCE SEQ_OKO_OPPDRAG_ENHET_120;
DROP SEQUENCE SEQ_OKO_OPPDRAG_LINJE_150;
DROP SEQUENCE SEQ_OKO_ATTESTANT_180;
DROP SEQUENCE SEQ_OKO_REFUSJONSINFO_156;
DROP SEQUENCE SEQ_OKO_GRAD_170;
DROP SEQUENCE SEQ_OPPDRAG_KVITTERING;
DROP SEQUENCE SEQ_TILKJENT_YTELSE;
DROP SEQUENCE SEQ_TY_BEHANDLING_INFO;
DROP SEQUENCE SEQ_TILKJENT_YTELSE_PERIODE;
DROP SEQUENCE SEQ_TILKJENT_YTELSE_ANDEL;
DROP SEQUENCE SEQ_TY_FERIEPENGER;
DROP SEQUENCE SEQ_OKO_OMPOSTERING_116;

DROP VIEW V_GR_SIMULERING;
DROP VIEW V_SIMULERING_RESULTAT;
DROP VIEW V_SIMULERING_MOTTAKER;
DROP VIEW V_SIMULERT_POSTERING;
DROP VIEW V_SIMULERING_XML;


