ALTER TABLE PROSESS_TASK ADD (
   SISTE_KJOERING_PLUKK_TS TIMESTAMP(6)
);
COMMENT ON COLUMN PROSESS_TASK.SISTE_KJOERING_PLUKK_TS IS 'siste gang tasken ble forsøkt plukket (klargjort til kjøring)';

ALTER TABLE PROSESS_TASK_TYPE ADD (
   CRON_EXPRESSION VARCHAR2(200 CHAR)
);
COMMENT ON COLUMN PROSESS_TASK_TYPE.CRON_EXPRESSION IS 'Cron-expression for når oppgaven skal kjøres på nytt';
