INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.nextval, 'KLASSE_KODE', '-', NULL, 'udefinert', 'ignorert klasse kode', 'NB', to_date('01.01.2000', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.nextval, 'FAG_OMRAADE_KODE', '-', NULL, 'udefinert', 'ignorert klasse kode', 'NB', to_date('01.01.2000', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.nextval, 'POSTERING_TYPE', '-', NULL, 'udefinert', 'ignorert klasse kode', 'NB', to_date('01.01.2000', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'));

-- retter eksisterende kodeverdier
UPDATE KODELISTE SET KODE = 'FEIL' WHERE KODE = 'FEILUTBETALING' AND KODEVERK = 'POSTERING_TYPE';
UPDATE KODELISTE SET KODE = 'SKAT' WHERE KODE = 'FORSKUDSSKATT' AND KODEVERK = 'POSTERING_TYPE';
UPDATE KODELISTE SET KODE = 'YTEL' WHERE KODE = 'YTELSE' AND KODEVERK = 'POSTERING_TYPE';