CREATE TABLE SIMULERING_XML
(
  "ID" NUMBER(19, 0),
  "BEHANDLING_ID" NUMBER(19, 0) NOT NULL,
  "REQUEST_XML" CLOB NOT NULL,
  "RESPONSE_XML" CLOB NULL,
  "OPPRETTET_AV" VARCHAR2(200 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
  "ENDRET_AV" VARCHAR2(200 CHAR),
  "ENDRET_TID" TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_SIMULERING_XML MINVALUE 1 START WITH 100000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE SIMULERING_XML IS 'Tabell for XML mot simulering som vi sender og mottar';
COMMENT ON COLUMN SIMULERING_XML.ID IS 'Primary key';
COMMENT ON COLUMN SIMULERING_XML.BEHANDLING_ID IS 'Behandlingen spørringen gjelder';
COMMENT ON COLUMN SIMULERING_XML.REQUEST_XML IS 'Request XML som sendes til simuleringtjenesten';
COMMENT ON COLUMN SIMULERING_XML.RESPONSE_XML IS 'Respons XML fra simuleringtjenesten';

ALTER TABLE SIMULERING_XML ADD CONSTRAINT PK_SIMULERING_XML PRIMARY KEY (ID) ENABLE;