DROP TABLE OKO_ATTESTANT_180 CASCADE CONSTRAINTS;
DROP TABLE OKO_GRAD_170 CASCADE CONSTRAINTS;
DROP TABLE OKO_REFUSJONSINFO_156 CASCADE CONSTRAINTS;
DROP TABLE OKO_OPPDRAG_LINJE_150 CASCADE CONSTRAINTS;
DROP TABLE OKO_OPPDRAG_ENHET_120 CASCADE CONSTRAINTS;
DROP TABLE OKO_OMPOSTERING_116 CASCADE CONSTRAINTS;
DROP TABLE OKO_AVSTEMMING_115 CASCADE CONSTRAINTS;
DROP TABLE OPPDRAG_KVITTERING CASCADE CONSTRAINTS;
DROP TABLE OKO_OPPDRAG_110 CASCADE CONSTRAINTS;
DROP TABLE OPPDRAG_KONTROLL CASCADE CONSTRAINTS;
DROP TABLE TY_FERIEPENGER CASCADE CONSTRAINTS;
DROP TABLE TILKJENT_YTELSE_ANDEL CASCADE CONSTRAINTS;
DROP TABLE TILKJENT_YTELSE_PERIODE CASCADE CONSTRAINTS;
DROP TABLE TY_BEHANDLING_INFO CASCADE CONSTRAINTS;
DROP TABLE TILKJENT_YTELSE CASCADE CONSTRAINTS;

DROP TABLE PROSESS_TASK_FEILHAND CASCADE CONSTRAINTS;
DROP TABLE PROSESS_TASK_TYPE CASCADE CONSTRAINTS;
DROP TABLE PROSESS_TASK CASCADE CONSTRAINTS;
DROP TABLE FAGSAK_PROSESS_TASK CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_OPPDRAG_KONTROLL;
DROP SEQUENCE SEQ_OKO_AVSTEMMING_115;
DROP SEQUENCE SEQ_OKO_OPPDRAG_110;
DROP SEQUENCE SEQ_OKO_OPPDRAG_ENHET_120;
DROP SEQUENCE SEQ_OKO_OPPDRAG_LINJE_150;
DROP SEQUENCE SEQ_OKO_ATTESTANT_180;
DROP SEQUENCE SEQ_OKO_REFUSJONSINFO_156;
DROP SEQUENCE SEQ_OKO_GRAD_170;
DROP SEQUENCE SEQ_OPPDRAG_KVITTERING;
DROP SEQUENCE SEQ_TILKJENT_YTELSE;
DROP SEQUENCE SEQ_TY_BEHANDLING_INFO;
DROP SEQUENCE SEQ_TILKJENT_YTELSE_PERIODE;
DROP SEQUENCE SEQ_TILKJENT_YTELSE_ANDEL;
DROP SEQUENCE SEQ_TY_FERIEPENGER;
DROP SEQUENCE SEQ_OKO_OMPOSTERING_116;

DROP SEQUENCE SEQ_FAGSAK_PROSESS_TASK;
DROP SEQUENCE SEQ_PROSESS_TASK;
DROP SEQUENCE SEQ_PROSESS_TASK_GRUPPE;

DROP VIEW V_GR_SIMULERING;
DROP VIEW V_SIMULERING_RESULTAT;
DROP VIEW V_SIMULERING_MOTTAKER;
DROP VIEW V_SIMULERT_POSTERING;
DROP VIEW V_SIMULERING_XML;


