Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','ARENA','AO01','Arena',to_date('13.02.2010','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','GRISEN','AO11','Grisen',to_date('27.01.2011','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','GOSYS','FS22','Gosys',to_date('25.04.2009','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','INFOTRYGD','IT01','Infotrygd',to_date('13.02.2010','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','HJE_HEL_ORT','OEBS','Hjelpemidler, Helsetjenester og Ort. Hjelpemidler',to_date('13.02.2010','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','PESYS','PP01','Pesys',to_date('10.12.2011','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','VENTELONN','V2','Ventelønn',to_date('13.02.2010','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','UNNTAK','UFM','Unntak',to_date('01.01.2010','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','FPSAK','FS36','Vedtaksløsning Foreldrepenger',to_date('28.06.2017','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAGSYSTEM','-',null,'Ikke definert',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'MOTTAKER_TYPE','BRUKER',null,'Bruker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'MOTTAKER_TYPE','ARBG_ORG',null,'ARBG_ORG',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'MOTTAKER_TYPE','ARBG_PRIV',null,'ARBG_PRIV',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAG_OMRAADE_KODE','FP',null,'Foreldrepenger',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAG_OMRAADE_KODE','SP',null,'Sykepenger',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FAG_OMRAADE_KODE','PP',null,'Pleiepenger',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'BETALING_TYPE','D',null,'Debit',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'BETALING_TYPE','K',null,'Kredit',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'POSTERING_TYPE','YTELSE',null,'Ytelse',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'POSTERING_TYPE','FEILUTBETALING',null,'Feilutbetaling',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'POSTERING_TYPE','FORSKUDSSKATT',null,'Forskudsskatt',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'POSTERING_TYPE','JUST',null,'Justering',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPATAL',null,'FPATAL',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPATFER',null,'FPATFER',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPATFRI',null,'FPATFRI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPATORD',null,'FPATORD',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPENAD-OP',null,'FPENAD-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPENFOD-OP',null,'FPENFOD-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPREFAGFER-IOP',null,'FPREFAGFER-IOP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPREFAG-IOP',null,'FPREFAG-IOP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPSNDDM-OP',null,'FPSNDDM-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPSNDFI',null,'FPSNDFI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPSNDJB-OP',null,'FPSNDJB-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FPSND-OP',null,'FPSND-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','FSKTSKAT',null,'FSKTSKAT',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','KL_KODE_FEIL_KORTTID',null,'KL_KODE_FEIL_KORTTID',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','TBMOTOBS',null,'TBMOTOBS',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','SPSND100D1DAGPFI',null,'SPSND100D1DAGPFI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'KLASSE_KODE','SPSND100D1DTRPFI',null,'SPSND100D1DTRPFI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));