CREATE VIEW V_GR_SIMULERING AS SELECT ID, BEHANDLING_ID, SIMULERING_ID, AKTIV, VERSJON, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID FROM GR_SIMULERING;

CREATE VIEW V_SIMULERING_RESULTAT AS SELECT ID, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID FROM SIMULERING_RESULTAT;

CREATE VIEW V_SIMULERING_MOTTAKER AS SELECT ID, SIMULERING_ID, MOTTAKER_TYPE, KL_MOTTAKER_TYPE, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID FROM SIMULERING_MOTTAKER;

CREATE VIEW V_SIMULERT_POSTERING AS SELECT ID, SIMULERING_MOTTAKER_ID, FAG_OMRAADE_KODE, FOM, TOM, BETALING_TYPE, BELOEP, POSTERING_TYPE, FORFALL, UTEN_INNTREKK, KL_FAG_OMRAADE_KODE, KL_BETALING_TYPE,
                                           KL_POSTERING_TYPE, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID FROM SIMULERT_POSTERING;

CREATE VIEW V_SIMULERING_XML AS SELECT ID, BEHANDLING_ID, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID FROM SIMULERING_XML;


COMMENT ON TABLE V_GR_SIMULERING IS 'View av GR_SIMULERING uten personidentifiserende opplysninger';
COMMENT ON COLUMN V_GR_SIMULERING.ID IS 'ID fra GR_SIMULERING';
COMMENT ON COLUMN V_GR_SIMULERING.BEHANDLING_ID IS 'BEHANDLING_ID fra GR_SIMULERING';
COMMENT ON COLUMN V_GR_SIMULERING.SIMULERING_ID IS 'SIMULERING_ID fra GR_SIMULERING';
COMMENT ON COLUMN V_GR_SIMULERING.AKTIV IS 'AKTIV fra GR_SIMULERING';
COMMENT ON COLUMN V_GR_SIMULERING.VERSJON IS 'VERSJON fra GR_SIMULERING';

COMMENT ON TABLE V_SIMULERING_RESULTAT IS 'View av SIMULERING_RESULTAT uten personidentifiserende opplysninger';
COMMENT ON COLUMN V_SIMULERING_RESULTAT.ID IS 'ID fra V_SIMULERING_RESULTAT';

COMMENT ON TABLE V_SIMULERING_MOTTAKER IS 'View av SIMULERING_MOTTAKER uten personidentifiserende opplysninger';
COMMENT ON COLUMN V_SIMULERING_MOTTAKER.ID IS 'ID fra SIMULERING_MOTTAKER';
COMMENT ON COLUMN V_SIMULERING_MOTTAKER.SIMULERING_ID IS 'SIMULERING_ID fra SIMULERING_MOTTAKER';
COMMENT ON COLUMN V_SIMULERING_MOTTAKER.MOTTAKER_TYPE IS 'MOTTAKER_TYPE fra SIMULERING_MOTTAKER';
COMMENT ON COLUMN V_SIMULERING_MOTTAKER.KL_MOTTAKER_TYPE IS 'KL_MOTTAKER_TYPE fra SIMULERING_MOTTAKER';

COMMENT ON TABLE V_SIMULERT_POSTERING IS 'View av SIMULERT_POSTERING uten personidentifiserende opplysninger';
COMMENT ON COLUMN V_SIMULERT_POSTERING.ID IS 'ID fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.SIMULERING_MOTTAKER_ID IS 'SIMULERING_MOTTAKER_ID fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.FAG_OMRAADE_KODE IS 'FAG_OMRAADE_KODE fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.FOM IS 'FOM fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.TOM IS 'TOM fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.BETALING_TYPE IS 'BETALING_TYPE fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.BELOEP IS 'BELOEP fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.POSTERING_TYPE IS 'POSTERING_TYPE fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.FORFALL IS 'FORFALL fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.UTEN_INNTREKK IS 'UTEN_INNTREKK fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.KL_FAG_OMRAADE_KODE IS 'KL_FAG_OMRAADE_KODE fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.KL_POSTERING_TYPE IS 'KL_POSTERING_TYPE fra SIMULERT_POSTERING';
COMMENT ON COLUMN V_SIMULERT_POSTERING.KL_BETALING_TYPE IS 'KL_BETALING_TYPE fra SIMULERT_POSTERING';

COMMENT ON TABLE V_SIMULERING_XML IS 'View av SIMULERING_XML uten personidentifiserende opplysninger';
COMMENT ON COLUMN V_SIMULERING_XML.ID IS 'ID fra SIMULERING_XML';
COMMENT ON COLUMN V_SIMULERING_XML.BEHANDLING_ID IS 'BEHANDLING_ID fra SIMULERING_XML';
