ALTER TABLE OKO_OPPDRAG_LINJE_150 DROP CONSTRAINT CHK_OKO_OPPDRAG_LINJE_150_4;

ALTER TABLE OKO_OPPDRAG_LINJE_150 ADD CONSTRAINT CHK_OKO_OPPDRAG_LINJE_150_4
CHECK (KODE_KLASSIFIK IN ('FPENFOD-OP', 'FPENAD-OP', 'FPATORD', 'FPATFRI', 'FPSND-OP', 'FPATAL', 'FPATSJO', 'FPSNDDM-OP', 'FPSNDJB-OP', 'FPSNDFI', 'FPATFER', 'FPREFAG-IOP', 'FPREFAGFER-IOP'));

ALTER TABLE OKO_OPPDRAG_LINJE_150 ADD CONSTRAINT CHK_OKO_OPPDRAG_LINJE_150_5 CHECK (FRADRAG_TILLEGG IN ('T'));