ALTER TABLE GR_SIMULERING ADD SIMULERING_KJOERT_DATO TIMESTAMP(3);

UPDATE GR_SIMULERING SET simulering_kjoert_dato = opprettet_tid where simulering_kjoert_dato is null;

ALTER TABLE GR_SIMULERING MODIFY SIMULERING_KJOERT_DATO NOT NULL;

COMMENT ON COlUMN "GR_SIMULERING"."SIMULERING_KJOERT_DATO" IS 'Tidspunkt for når simulering ble utført.';