CREATE TABLE OKO_OMPOSTERING_116 (
  ID NUMBER (19,0) not null,
  OKO_OPPDRAG_110_ID NUMBER (19,0) not null,
  OM_POSTERING varchar2(1 char) not null check (OM_POSTERING IN ('J', 'N')),
  DATO_OMPOSTER_FOM DATE,
  TIDSPKT_REG varchar2(30 char) not null,
  SAKSBEH_ID varchar2(10 char) not null,
  OPPRETTET_AV varchar2(20 char) default 'VL' not null,
  OPPRETTET_TID timestamp(3) default systimestamp not null,
  ENDRET_AV varchar2(20 char),
  ENDRET_TID timestamp(3),
  CONSTRAINT PK_OKO_OMPOSTERING_116 PRIMARY KEY (ID),
  CONSTRAINT FK_OKO_OMPOSTERING_116_1 FOREIGN KEY (OKO_OPPDRAG_110_ID) REFERENCES OKO_OPPDRAG_110 (ID)
);

CREATE SEQUENCE SEQ_OKO_OMPOSTERING_116 MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE INDEX IDX_OKO_OMPOSTERING_116_1 ON OKO_OMPOSTERING_116 (OKO_OPPDRAG_110_ID);

COMMENT ON TABLE OKO_OMPOSTERING_116 IS 'Inneholder de relevante verdier som mappes og sender med i request melding. (Tabell fra Økonomi).';
COMMENT ON COLUMN OKO_OMPOSTERING_116.ID IS 'Primærnøkkel.';
COMMENT ON COLUMN OKO_OMPOSTERING_116.OKO_OPPDRAG_110_ID IS 'Fremmednøkkel mot OKO_OPPDRAG_110.';
COMMENT ON COLUMN OKO_OMPOSTERING_116.OM_POSTERING IS 'Om inntrekk skal være av eller på. J = uten inntrekk, N = med inntrekk.';
COMMENT ON COLUMN OKO_OMPOSTERING_116.DATO_OMPOSTER_FOM IS 'Endringsdato for vedtaket.';
COMMENT ON COLUMN OKO_OMPOSTERING_116.TIDSPKT_REG IS 'Tidspunkt registrert.';
COMMENT ON COLUMN OKO_OMPOSTERING_116.SAKSBEH_ID IS 'Saksbehandlers id.';
