ALTER TABLE SIMULERING_RESULTAT MODIFY KJOERES_DATO DATE NULL;

ALTER TABLE SIMULERT_POSTERING ADD ("FORFALL" DATE NOT NULL);
COMMENT ON COLUMN SIMULERT_POSTERING.FORFALL IS 'Forfalls dato fra simulering resultat';