ALTER TABLE GR_SIMULERING ADD (YTELSE_TYPE VARCHAR2(100 CHAR) DEFAULT '-' NOT NULL,
     KL_YTELSE_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('YTELSE_TYPE') VIRTUAL VISIBLE);

ALTER TABLE GR_SIMULERING
  ADD CONSTRAINT FK_GR_SIMULERING_02 FOREIGN KEY (KL_YTELSE_TYPE, YTELSE_TYPE) REFERENCES KODELISTE (kodeverk, kode);

CREATE INDEX IDX_GR_SIMULERING_2 ON GR_SIMULERING (YTELSE_TYPE);

COMMENT ON COLUMN GR_SIMULERING.YTELSE_TYPE IS 'Type ytelse til ekstern behandling';
COMMENT ON COLUMN GR_SIMULERING.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
