
--------------------------------------------------------
--  DDL for Table SIMULERING_RESULTAT
--------------------------------------------------------

CREATE TABLE "SIMULERING_RESULTAT"
(
  "ID"  NUMBER(19, 0),
  "KJOERES_DATO"   DATE NOT NULL,
  "OPPRETTET_AV"   VARCHAR2(200 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID"  TIMESTAMP(3)       DEFAULT systimestamp,
  "ENDRET_AV"      VARCHAR2(200 CHAR),
  "ENDRET_TID"     TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_SIMULERING_RESULTAT MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON COLUMN "SIMULERING_RESULTAT"."ID" IS 'Primary Key';
COMMENT ON COLUMN "SIMULERING_RESULTAT"."KJOERES_DATO" IS 'Når kjøring av beregning foretas';
COMMENT ON TABLE "SIMULERING_RESULTAT" IS 'Inneholder lister av simuleringResultat resultat';

--------------------------------------------------------
--  Primary Key
--------------------------------------------------------

ALTER TABLE "SIMULERING_RESULTAT"
  ADD CONSTRAINT "PK_SIMULERING_RESULTAT" PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table GR_SIMULERING
--------------------------------------------------------
CREATE TABLE "GR_SIMULERING"
(
  "ID"  NUMBER(19, 0),
  "BEHANDLING_ID" NUMBER(19,0) NOT NULL,
  "SIMULERING_ID" NUMBER(19, 0) NOT NULL,
  "AKTIV"         VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  "VERSJON"       NUMBER(19,0) DEFAULT 0 NOT NULL,
  "OPPRETTET_AV"   VARCHAR2(200 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID"  TIMESTAMP(3)       DEFAULT systimestamp,
  "ENDRET_AV"      VARCHAR2(200 CHAR),
  "ENDRET_TID"     TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_GR_SIMULERING MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON COLUMN "GR_SIMULERING"."ID" IS 'Primary Key';
COMMENT ON COLUMN "GR_SIMULERING"."BEHANDLING_ID" IS 'FK:BEHANDLING Foreign key';
COMMENT ON COLUMN "GR_SIMULERING"."SIMULERING_ID" IS 'FK:Simulering';
COMMENT ON COLUMN "GR_SIMULERING"."AKTIV" IS 'Angir status av Simulering';
COMMENT ON COLUMN "GR_SIMULERING"."VERSJON" IS 'Version av simuleringResultat';
COMMENT ON TABLE  "GR_SIMULERING" IS 'Inneholder version liste av simuleringResultat';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------

ALTER TABLE "GR_SIMULERING"
  ADD CONSTRAINT "PK_GR_SIMULERING" PRIMARY KEY ("ID") ENABLE;

CREATE INDEX "IDX_GR_SIMULERING_1"
  ON "GR_SIMULERING" ("SIMULERING_ID");

--------------------------------------------------------
--  Ref Constraints for Table GR_SIMULERING
--------------------------------------------------------

ALTER TABLE "GR_SIMULERING"
  ADD CONSTRAINT "FK_GR_SIMULERING_01" FOREIGN KEY ("SIMULERING_ID")
REFERENCES "SIMULERING_RESULTAT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table SIMULERING_MOTTAKER
--------------------------------------------------------
CREATE TABLE "SIMULERING_MOTTAKER"
(
  "ID"  NUMBER(19, 0),
  "SIMULERING_ID" NUMBER(19, 0) NOT NULL,
  "MOTTAKER_NUMMER"  VARCHAR2(11 CHAR ),
  "MOTTAKER_TYPE"  VARCHAR2(100 CHAR) NOT NULL,
  "KL_MOTTAKER_TYPE"  VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('MOTTAKER_TYPE') VIRTUAL VISIBLE,
  "OPPRETTET_AV"   VARCHAR2(200 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID"  TIMESTAMP(3)       DEFAULT systimestamp,
  "ENDRET_AV"      VARCHAR2(200 CHAR),
  "ENDRET_TID"     TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_SIMULERING_MOTTAKER MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON COLUMN "SIMULERING_MOTTAKER"."MOTTAKER_NUMMER" IS 'Utbetalingsmottaker (fnr/orgnr)';
COMMENT ON COLUMN "SIMULERING_MOTTAKER"."MOTTAKER_TYPE" IS 'Type av mottaker';
COMMENT ON COLUMN "SIMULERING_MOTTAKER"."KL_MOTTAKER_TYPE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE  "SIMULERING_MOTTAKER" IS 'Inneholder mottaker informasjon';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------

ALTER TABLE "SIMULERING_MOTTAKER"
  ADD CONSTRAINT "PK_SIMULERING_MOTTAKER" PRIMARY KEY ("ID") ENABLE;

CREATE INDEX "IDX_SIMULERING_MOTTAKER_1"
  ON "SIMULERING_MOTTAKER" ("SIMULERING_ID");

CREATE INDEX "IDX_SIMULERING_MOTTAKER_2"
  ON "SIMULERING_MOTTAKER" ("MOTTAKER_TYPE");

--------------------------------------------------------
--  Ref Constraints for Table SIMULERING_MOTTAKER
--------------------------------------------------------

ALTER TABLE "SIMULERING_MOTTAKER"
  ADD CONSTRAINT "FK_SIMULERING_MOTTAKER_01" FOREIGN KEY ("SIMULERING_ID")
REFERENCES "SIMULERING_RESULTAT" ("ID") ENABLE;

ALTER TABLE "SIMULERING_MOTTAKER"
  ADD CONSTRAINT "FK_SIMULERING_MOTTAKER_02" FOREIGN KEY ("MOTTAKER_TYPE","KL_MOTTAKER_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

--------------------------------------------------------
--  DDL for Table SIMULERING_POSTERING
--------------------------------------------------------

CREATE TABLE "SIMULERT_POSTERING"
(
  "ID"            NUMBER(19, 0),
  "SIMULERING_MOTTAKER_ID" NUMBER(19, 0) NOT NULL,
  "FAG_OMRAADE_KODE"  VARCHAR2(100 CHAR) NOT NULL,
  "KONTO"         VARCHAR2(19 CHAR) NOT NULL,
  "FOM"           DATE NOT NULL,
  "TOM"           DATE NOT NULL,
  "BETALING_TYPE" VARCHAR2(100 CHAR) NOT NULL,
  "BELOEP"         NUMBER(12,2) NOT NULL,
  "POSTERING_TYPE" VARCHAR2(100 CHAR) NOT NULL,
  "KLASSE_KODE"   VARCHAR2(100 CHAR) NOT NULL,
  "KL_FAG_OMRAADE_KODE"  VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAG_OMRAADE_KODE') VIRTUAL VISIBLE,
  "KL_BETALING_TYPE" VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('BETALING_TYPE') VIRTUAL VISIBLE,
  "KL_POSTERING_TYPE" VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('POSTERING_TYPE') VIRTUAL VISIBLE,
  "KL_KLASSE_KODE"   VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KLASSE_KODE') VIRTUAL VISIBLE,
  "OPPRETTET_AV"  VARCHAR2(200 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID" TIMESTAMP(3) DEFAULT systimestamp,
  "ENDRET_AV"     VARCHAR2(200 CHAR),
  "ENDRET_TID"    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_SIMULERT_POSTERING MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON COLUMN "SIMULERT_POSTERING"."ID" IS 'Primary Key';
COMMENT ON COLUMN "SIMULERT_POSTERING"."SIMULERING_MOTTAKER_ID" IS 'FK:SIMULERING_MOTTAKER';
COMMENT ON COLUMN "SIMULERT_POSTERING"."FAG_OMRAADE_KODE" IS 'Fagområde.Mulige verdier: FP, SP, PP';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KONTO" IS 'Hovedkontonr||underkontonr||formålskode|| aktivitetskode';
COMMENT ON COLUMN "SIMULERT_POSTERING"."FOM" IS 'Første dag av Simulering Postering';
COMMENT ON COLUMN "SIMULERT_POSTERING"."TOM" IS 'Siste dag av Simulering Postering';
COMMENT ON COLUMN "SIMULERT_POSTERING"."BETALING_TYPE" IS 'Angir om det er kredit-post eller debet-post';
COMMENT ON COLUMN "SIMULERT_POSTERING"."BELOEP" IS 'Beloep av Simulering Postering';
COMMENT ON COLUMN "SIMULERT_POSTERING"."POSTERING_TYPE" IS 'Type av postering';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KLASSE_KODE" IS 'Klasse kode av postering';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KL_FAG_OMRAADE_KODE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KL_BETALING_TYPE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KL_POSTERING_TYPE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN "SIMULERT_POSTERING"."KL_KLASSE_KODE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE  "SIMULERT_POSTERING" IS 'Inneholder detaljer av simuleringResultat';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------
ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "PK_SIMULERT_POSTERING" PRIMARY KEY ("ID") ENABLE;

CREATE INDEX "IDX_SIMULERT_POSTERING_1"
  ON "SIMULERT_POSTERING" ("SIMULERING_MOTTAKER_ID");

CREATE INDEX "IDX_SIMULERT_POSTERING_2"
  ON "SIMULERT_POSTERING" ("FAG_OMRAADE_KODE");

CREATE INDEX "IDX_SIMULERT_POSTERING_3"
  ON "SIMULERT_POSTERING" ("BETALING_TYPE");

CREATE INDEX "IDX_SIMULERT_POSTERING_4"
  ON "SIMULERT_POSTERING" ("POSTERING_TYPE");

CREATE INDEX "IDX_SIMULERT_POSTERING_5"
  ON "SIMULERT_POSTERING" ("KLASSE_KODE");

--------------------------------------------------------
--  Ref Constraints for Table SIMULERT_POSTERING
--------------------------------------------------------

ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "FK_SIMULERT_POSTERING_01" FOREIGN KEY ("SIMULERING_MOTTAKER_ID")
REFERENCES "SIMULERING_MOTTAKER" ("ID") ENABLE;

ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "FK_SIMULERT_POSTERING_02" FOREIGN KEY ("FAG_OMRAADE_KODE","KL_FAG_OMRAADE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "FK_SIMULERT_POSTERING_03" FOREIGN KEY ("BETALING_TYPE","KL_BETALING_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "FK_SIMULERT_POSTERING_04" FOREIGN KEY ("POSTERING_TYPE","KL_POSTERING_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE "SIMULERT_POSTERING"
  ADD CONSTRAINT "FK_SIMULERT_POSTERING_05" FOREIGN KEY ("KLASSE_KODE","KL_KLASSE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;