ALTER TABLE SIMULERT_POSTERING
ADD (SATS NUMBER(12,2),
     SATS_TYPE VARCHAR2(100 CHAR) DEFAULT '-' NOT NULL,
     KL_SATS_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('SATS_TYPE') VIRTUAL VISIBLE);

ALTER TABLE SIMULERT_POSTERING
  ADD CONSTRAINT FK_SIMULERT_POSTERING_06 FOREIGN KEY (KL_SATS_TYPE, SATS_TYPE) REFERENCES KODELISTE (kodeverk, kode);

CREATE INDEX IDX_SIMULERT_POSTERING_6 ON SIMULERT_POSTERING (SATS_TYPE);


COMMENT ON COLUMN SIMULERT_POSTERING.SATS IS 'Sats';
COMMENT ON COLUMN SIMULERT_POSTERING.SATS_TYPE IS 'Type sats';
COMMENT ON COLUMN SIMULERT_POSTERING.KL_SATS_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';